"use client";

import { FileText, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type ReportPreviewProps = {
	patientName: string;
	insurerName: string;
	diagnosis: string;
	reportBody?: {
		clinicalSummary?: string;
		history?: string;
		investigations?: string;
		treatmentPlan?: string;
		opinion?: string;
	};
};

export function ReportPreview({
	patientName,
	insurerName,
	diagnosis,
	reportBody,
}: ReportPreviewProps) {
	const hasContent =
		reportBody?.clinicalSummary ||
		reportBody?.history ||
		reportBody?.investigations ||
		reportBody?.treatmentPlan ||
		reportBody?.opinion;

	function handlePrint() {
		window.print();
	}

	return (
		<Card className="print:border-0 print:shadow-none">
			<CardHeader className="pb-3 print:pb-6">
				<div className="flex items-center justify-between">
					<CardTitle className="flex items-center gap-2 font-semibold text-lg">
						<FileText className="h-5 w-5 text-blue-600" />
						Medical Report Preview
					</CardTitle>
					<Button
						className="print:hidden"
						onClick={handlePrint}
						size="sm"
						variant="outline"
					>
						<Printer className="mr-1.5 h-3.5 w-3.5" />
						Print
					</Button>
				</div>
			</CardHeader>
			<CardContent className="space-y-6">
				{/* Header Section */}
				<div className="rounded-lg border border-gray-100 bg-gray-50 p-4 print:border-gray-300 print:bg-white">
					<div className="grid gap-3 sm:grid-cols-3">
						<div>
							<p className="font-medium text-muted-foreground text-xs uppercase tracking-wide">
								Patient
							</p>
							<p className="mt-1 font-medium text-gray-900 text-sm">
								{patientName}
							</p>
						</div>
						<div>
							<p className="font-medium text-muted-foreground text-xs uppercase tracking-wide">
								Insurer
							</p>
							<p className="mt-1 font-medium text-gray-900 text-sm">
								{insurerName}
							</p>
						</div>
						<div>
							<p className="font-medium text-muted-foreground text-xs uppercase tracking-wide">
								Primary Diagnosis
							</p>
							<p className="mt-1 font-medium text-gray-900 text-sm">
								{diagnosis}
							</p>
						</div>
					</div>
				</div>

				{!hasContent ? (
					<div className="rounded-lg border border-amber-100 bg-amber-50 px-4 py-8 text-center">
						<p className="text-amber-700 text-sm">
							No report content available. Please complete the report first.
						</p>
					</div>
				) : (
					<div className="space-y-5">
						{reportBody?.clinicalSummary && (
							<section>
								<h3 className="mb-2 font-semibold text-gray-900 text-sm">
									Clinical Summary
								</h3>
								<p className="whitespace-pre-wrap text-gray-700 text-sm leading-relaxed">
									{reportBody.clinicalSummary}
								</p>
							</section>
						)}

						{reportBody?.history && (
							<section>
								<h3 className="mb-2 font-semibold text-gray-900 text-sm">
									Relevant Past History
								</h3>
								<p className="whitespace-pre-wrap text-gray-700 text-sm leading-relaxed">
									{reportBody.history}
								</p>
							</section>
						)}

						{reportBody?.investigations && (
							<section>
								<h3 className="mb-2 font-semibold text-gray-900 text-sm">
									Examination &amp; Investigations
								</h3>
								<p className="whitespace-pre-wrap text-gray-700 text-sm leading-relaxed">
									{reportBody.investigations}
								</p>
							</section>
						)}

						{reportBody?.treatmentPlan && (
							<section>
								<h3 className="mb-2 font-semibold text-gray-900 text-sm">
									Proposed Treatment Plan
								</h3>
								<p className="whitespace-pre-wrap text-gray-700 text-sm leading-relaxed">
									{reportBody.treatmentPlan}
								</p>
							</section>
						)}

						{reportBody?.opinion && (
							<section className="rounded-lg border border-blue-100 bg-blue-50 p-4 print:border-gray-300 print:bg-white">
								<h3 className="mb-2 font-semibold text-blue-900 text-sm">
									Doctor&apos;s Opinion
								</h3>
								<p className="whitespace-pre-wrap text-blue-800 text-sm leading-relaxed">
									{reportBody.opinion}
								</p>
							</section>
						)}
					</div>
				)}

				{/* Footer for print */}
				<div className="hidden border-gray-200 border-t pt-4 print:block">
					<p className="text-muted-foreground text-xs">
						Generated by MediSure GL System • {new Date().toLocaleDateString()}
					</p>
				</div>
			</CardContent>
		</Card>
	);
}
